import type { RedcapRow } from '@/lib/redcap/client';
import { findUnknownFields, type CatalogIssue } from './validate';
import type { CatalogDoc } from './types';

/**
 * Compares the catalog against REDCap's live data dictionary.
 *
 * REDCap's schema is edited by people, not by this repository, so a form can be
 * renamed or retired without anything here noticing. That had already happened:
 * the dashboard tracked an instrument REDCap does not have, whose _complete
 * field therefore read empty for every record — a form permanently stuck at 0%
 * whose owner could never finish it.
 */

export interface DriftReport {
  /** Instruments the catalog reads that REDCap does not have. */
  missingForms: string[];
  /** Instruments REDCap has that no work unit tracks. */
  untrackedForms: string[];
  /** Fields referenced by the catalog that REDCap does not have. */
  unknownFields: CatalogIssue[];
  /** True when nothing needs the manager's attention. */
  clean: boolean;
}

/** Field names REDCap answers to, including the auto-generated _complete ones. */
export function knownFieldNames(metadata: RedcapRow[]): Set<string> {
  const fields = new Set<string>();
  const instruments = new Set<string>();

  for (const row of metadata) {
    if (row.field_name) fields.add(row.field_name);
    if (row.form_name) instruments.add(row.form_name);
  }
  // <form>_complete is generated by REDCap and never listed in the dictionary.
  for (const form of instruments) fields.add(`${form}_complete`);

  return fields;
}

export function instrumentNames(metadata: RedcapRow[]): Set<string> {
  return new Set(metadata.map(row => row.form_name).filter(Boolean));
}

export function detectDrift(catalog: CatalogDoc, metadata: RedcapRow[]): DriftReport {
  const instruments = instrumentNames(metadata);
  const catalogForms = new Set(catalog.units.map(unit => unit.redcapForm));

  const missingForms = [...catalogForms].filter(form => !instruments.has(form)).sort();
  const untrackedForms = [...instruments].filter(form => !catalogForms.has(form)).sort();
  const unknownFields = findUnknownFields(catalog, knownFieldNames(metadata));

  return {
    missingForms,
    untrackedForms,
    unknownFields,
    clean: missingForms.length === 0 && untrackedForms.length === 0 && unknownFields.length === 0,
  };
}
